version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo
    
    networks:
      - bridge
    
    volumes:
      - ./server/:/server/
      - /server/node_modules


  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000


  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - bridge

networks:
  bridge:
    driver: bridge


volumes:
  mongo-data:

