// module.exports.data = [
//   {
//     name: "Apple Inc.",
//     symbol: "AAPL",
//     sector: "Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Amazon.com, Inc.",
//     symbol: "AMZN",
//     sector: "Consumer Discretionary",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Alphabet Inc. (Class A)",
//     symbol: "GOOGL",
//     sector: "Communication Services",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Alphabet Inc. (Class C)",
//     symbol: "GOOG",
//     sector: "Communication Services",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Microsoft Corporation",
//     symbol: "MSFT",
//     sector: "Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Facebook, Inc. (Class A)",
//     symbol: "FB",
//     sector: "Communication Services",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Tesla, Inc.",
//     symbol: "TSLA",
//     sector: "Consumer Discretionary",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Berkshire Hathaway Inc. (Class B)",
//     symbol: "BRK.B",
//     sector: "Financials",
//     exchange: "NYSE",
//   },
//   {
//     name: "JPMorgan Chase & Co.",
//     symbol: "JPM",
//     sector: "Financials",
//     exchange: "NYSE",
//   },
//   {
//     name: "Johnson & Johnson",
//     symbol: "JNJ",
//     sector: "Health Care",
//     exchange: "NYSE",
//   },
//   {
//     name: "Procter & Gamble Company",
//     symbol: "PG",
//     sector: "Consumer Staples",
//     exchange: "NYSE",
//   },
//   {
//     name: "Visa Inc.",
//     symbol: "V",
//     sector: "Information Technology",
//     exchange: "NYSE",
//   },
//   {
//     name: "Walmart Inc.",
//     symbol: "WMT",
//     sector: "Consumer Staples",
//     exchange: "NYSE",
//   },
//   {
//     name: "The Coca-Cola Company",
//     symbol: "KO",
//     sector: "Consumer Staples",
//     exchange: "NYSE",
//   },
//   {
//     name: "Intel Corporation",
//     symbol: "INTC",
//     sector: "Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "NVIDIA Corporation",
//     symbol: "NVDA",
//     sector: "Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Advanced Micro Devices, Inc.",
//     symbol: "AMD",
//     sector: "Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Netflix, Inc.",
//     symbol: "NFLX",
//     sector: "Communication Services",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "PayPal Holdings, Inc.",
//     symbol: "PYPL",
//     sector: "Information Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Salesforce.com, Inc.",
//     symbol: "CRM",
//     sector: "Information Technology",
//     exchange: "NYSE",
//   },
//   {
//     name: "Adobe Inc.",
//     symbol: "ADBE",
//     sector: "Information Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Cisco Systems, Inc.",
//     symbol: "CSCO",
//     sector: "Information Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Toyota Motor Corporation",
//     symbol: "TM",
//     sector: "Consumer Discretionary",
//     exchange: "NYSE",
//   },
//   {
//     name: "Honda Motor Co., Ltd.",
//     symbol: "HMC",
//     sector: "Consumer Discretionary",
//     exchange: "NYSE",
//   },
//   {
//     name: "Sony Corporation",
//     symbol: "SONY",
//     sector: "Communication Services",
//     exchange: "NYSE",
//   },
//   {
//     name: "Samsung Electronics Co., Ltd.",
//     symbol: "SSNLF",
//     sector: "Information Technology",
//     exchange: "OTC Markets",
//   },
//   {
//     name: "Taiwan Semiconductor Manufacturing Company Limited",
//     symbol: "TSM",
//     sector: "Information Technology",
//     exchange: "NYSE",
//   },
//   {
//     name: "Alibaba Group Holding Limited",
//     symbol: "BABA",
//     sector: "Consumer Discretionary",
//     exchange: "NYSE",
//   },
//   {
//     name: "Baidu, Inc.",
//     symbol: "BIDU",
//     sector: "Communication Services",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "JD.com, Inc.",
//     symbol: "JD",
//     sector: "Consumer Discretionary",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Tencent Holdings Limited",
//     symbol: "TCEHY",
//     sector: "Communication Services",
//     exchange: "OTC Markets",
//   },
//   {
//     name: "Vodafone Group Plc",
//     symbol: "VOD",
//     sector: "Communication Services",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "BP p.l.c.",
//     symbol: "BP",
//     sector: "Energy",
//     exchange: "NYSE",
//   },
//   {
//     name: "Exxon Mobil Corporation",
//     symbol: "XOM",
//     sector: "Energy",
//     exchange: "NYSE",
//   },
//   {
//     name: "Chevron Corporation",
//     symbol: "CVX",
//     sector: "Energy",
//     exchange: "NYSE",
//   },
//   {
//     name: "Royal Dutch Shell plc",
//     symbol: "RDS-A",
//     sector: "Energy",
//     exchange: "NYSE",
//   },
//   {
//     name: "AT&T Inc.",
//     symbol: "T",
//     sector: "Communication Services",
//     exchange: "NYSE",
//   },
//   {
//     name: "Verizon Communications Inc.",
//     symbol: "VZ",
//     sector: "Communication Services",
//     exchange: "NYSE",
//   },
//   {
//     name: "The Procter & Gamble Company",
//     symbol: "PG",
//     sector: "Consumer Staples",
//     exchange: "NYSE",
//   },
//   {
//     name: "Nestle S.A.",
//     symbol: "NSRGF",
//     sector: "Consumer Staples",
//     exchange: "OTC Markets",
//   },
//   {
//     name: "Unilever PLC",
//     symbol: "UL",
//     sector: "Consumer Staples",
//     exchange: "NYSE",
//   },
//   {
//     name: "PepsiCo, Inc.",
//     symbol: "PEP",
//     sector: "Consumer Staples",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Johnson & Johnson",
//     symbol: "JNJ",
//     sector: "Health Care",
//     exchange: "NYSE",
//   },
//   {
//     name: "Pfizer Inc.",
//     symbol: "PFE",
//     sector: "Health Care",
//   },
//   {
//     name: "NVIDIA Corporation",
//     symbol: "NVDA",
//     sector: "Information Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Adobe Inc.",
//     symbol: "ADBE",
//     sector: "Information Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Salesforce.com, Inc.",
//     symbol: "CRM",
//     sector: "Information Technology",
//     exchange: "NYSE",
//   },
//   {
//     name: "PayPal Holdings, Inc.",
//     symbol: "PYPL",
//     sector: "Information Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Zoom Video Communications, Inc.",
//     symbol: "ZM",
//     sector: "Communication Services",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Netflix, Inc.",
//     symbol: "NFLX",
//     sector: "Communication Services",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Amazon.com, Inc.",
//     symbol: "AMZN",
//     sector: "Consumer Discretionary",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Walmart Inc.",
//     symbol: "WMT",
//     sector: "Consumer Staples",
//     exchange: "NYSE",
//   },
//   {
//     name: "Costco Wholesale Corporation",
//     symbol: "COST",
//     sector: "Consumer Staples",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Alphabet Inc.",
//     symbol: "GOOGL",
//     sector: "Communication Services",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Microsoft Corporation",
//     symbol: "MSFT",
//     sector: "Information Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Apple Inc.",
//     symbol: "AAPL",
//     sector: "Information Technology",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Facebook, Inc.",
//     symbol: "FB",
//     sector: "Communication Services",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Tesla, Inc.",
//     symbol: "TSLA",
//     sector: "Consumer Discretionary",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Johnson Controls International plc",
//     symbol: "JCI",
//     sector: "Industrials",
//     exchange: "NYSE",
//   },
//   {
//     name: "General Electric Company",
//     symbol: "GE",
//     sector: "Industrials",
//     exchange: "NYSE",
//   },
//   {
//     name: "Boeing Company",
//     symbol: "BA",
//     sector: "Industrials",
//     exchange: "NYSE",
//   },
//   {
//     name: "Ford Motor Company",
//     symbol: "F",
//     sector: "Consumer Discretionary",
//     exchange: "NYSE",
//   },
//   {
//     name: "General Motors Company",
//     symbol: "GM",
//     sector: "Consumer Discretionary",
//     exchange: "NYSE",
//   },
//   {
//     name: "Caterpillar Inc.",
//     symbol: "CAT",
//     sector: "Industrials",
//     exchange: "NYSE",
//   },
//   {
//     name: "3M Company",
//     symbol: "MMM",
//     sector: "Industrials",
//     exchange: "NYSE",
//   },
//   {
//     name: "The Coca-Cola Company",
//     symbol: "KO",
//     sector: "Consumer Staples",
//     exchange: "NYSE",
//   },
//   {
//     name: "Johnson & Johnson",
//     symbol: "JNJ",
//     sector: "Health Care",
//     exchange: "NYSE",
//   },
//   {
//     name: "Merck & Co., Inc.",
//     symbol: "MRK",
//     sector: "Health Care",
//     exchange: "NYSE",
//   },
//   {
//     name: "Pfizer Inc.",
//     symbol: "PFE",
//     sector: "Health Care",
//     exchange: "NYSE",
//   },
//   {
//     name: "Abbott Laboratories",
//     symbol: "ABT",
//     sector: "Health Care",
//     exchange: "NYSE",
//   },
//   {
//     name: "UnitedHealth Group Incorporated",
//     symbol: "UNH",
//     sector: "Health Care",
//     exchange: "NYSE",
//   },
//   {
//     name: "Humana Inc.",
//     symbol: "HUM",
//     sector: "Health Care",
//     exchange: "NYSE",
//   },
//   {
//     name: "AstraZeneca PLC",
//     symbol: "AZN",
//     sector: "Health Care",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Novo Nordisk A/S",
//     symbol: "NVO",
//     sector: "Health Care",
//     exchange: "NYSE",
//   },
//   {
//     name: "Takeda Pharmaceutical Company Limited",
//     symbol: "TAK",
//     sector: "Health Care",
//     exchange: "NYSE",
//   },
//   {
//     name: "Sony Corporation",
//     symbol: "SNE",
//     sector: "Communication Services",
//     exchange: "NYSE",
//   },
//   {
//     name: "Baidu, Inc.",
//     symbol: "BIDU",
//     sector: "Communication Services",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Alibaba Group Holding Limited",
//     symbol: "BABA",
//     sector: "Consumer Discretionary",
//     exchange: "NYSE",
//   },
//   {
//     name: "JD.com, Inc.",
//     symbol: "JD",
//     sector: "Consumer Discretionary",
//     exchange: "NASDAQ",
//   },
//   {
//     name: "Procter & Gamble Company",
//     symbol: "PG",
//     sector: "Consumer Staples",
//     exchange: "NYSE",
//   },
//   {
//     name: "Nestle S.A.",
//     symbol: "NSRGF",
//     sector: "Consumer Staples",
//     exchange: "OTC Markets",
//   },
//   {
//     name: "Unilever N.V.",
//     symbol: "UN",
//     sector: "Consumer Staples",
//     exchange: "NYSE",
//   },
//   {
//     name: "Diageo plc",
//     symbol: "DEO",
//     sector: "Consumer Staples",
//     exchange: "NYSE",
//   },
//   {
//     name: "Mastercard Incorporated",
//     symbol: "MA",
//     sector: "Information Technology",
//     exchange: "NYSE",
//   },
//   {
//     name: "Visa Inc.",
//     symbol: "V",
//     sector: "Information Technology",
//     exchange: "NYSE",
//   },
//   {
//     name: "International Business Machines Corporation",
//     symbol: "IBM",
//     sector: "Information Technology",
//     exchange: "NYSE",
//   },
//   {
//     name: "Accenture plc",
//     symbol: "ACN",
//     sector: "Information Technology",
//     exchange: "NYSE",
//   },
//   {
//     name: "Intel Corporation",
//     symbol: "INTC",
//     sector: "Information Technology",
//     exchange: "NASDAQ",
//   },
// ];

module.exports.data = [
  {
    name: "Copart Inc.",
    symbol: "CPRT",
  },
  {
    name: "FirstService Corp.",
    symbol: "FSV",
  },
  {
    name: "GWR Group Ltd",
    symbol: "GWR",
  },
  {
    name: "Alphabet Inc. (Class C)",
    symbol: "GOOG",
  },
  {
    name: "Twitter",
    symbol: "TWTR",
  },
  {
    name: "Facebook, Inc. (Class A)",
    symbol: "FB",
  },
  {
    name: "Tesla, Inc.",
    symbol: "TSLA",
  },
  {
    name: "Laurentian Bank of Canada",
    symbol: "LB",
  },
  {
    name: "LYFT Inc",
    symbol: "LYFT",
  },
  {
    name: "Matador Resources Co",
    symbol: "MTDR",
  },
  {
    name: "SINA Corp",
    symbol: "SINA",
  },
  {
    name: "Advanced Micro Devices, Inc.",
    symbol: "AMD",
  },
];
